config/routes.rb
Rails.application.routes.draw do
  root "landings#show"

  resource :landing
  resources :home

  resource :session do
    scope module: :sessions do
      # resources :transfers
      resource :magic_link
    end
  end

  namespace :my do
    resources :accounts
  end

  scope module: :account, as: :account do
    resources :users
    resource :join_code
    resources :invitations
    resource :payment
    # TODO: implement subscription operations later
    resource :subscription do
      # scope module: :subscriptions do
      #   resource :upgrade, only: :create
      #   resource :downgrade, only: :create
      # end
    end
    # resources :charges # billings?
  end

  namespace :webhooks do
    resource :creem
  end

  get "join/:code", to: "join_codes#new", as: :join
  post "join/:code", to: "join_codes#create"

  resources :account_invitations, param: :token, only: [ :show ] do
    scope module: :account_invitations do
      # resource :accept, only: [ :show, :update ], controller: :acceptances
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :users, only: [ :index, :show, :create ]
      resources :tokens, only: [ :create ]
    end
  end

  # Dashboard Engines
  namespace :admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"
    resource :stats
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  allow_unauthenticated_access

  def show
    render "home/index" unless authenticated?
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/show.html.erb
<% @page_title = "Home" %>

<div class="max-w-5xl py-4 prose mx-auto">
  <h1>Landing page</h1>
  <p class="text-gray-500">This is the landing page, <code>landings_controller#show</code> and <code>landings/show.html.erb</code>.</p>

  <div class="my-4 flex gap-4 items-center">
    <span class="text-lg font-bold">You are signed in as <code><%= Current.identity.email %></code>.</span>
    <%= button_to "Sign Out", session_path(script_name: nil), class: "btn btn-error btn-sm", method: :delete %>
  </div>

  <div class="mt-4 card bg-base-100 card-sm shadow-sm">
    <div class="card-body">
      <h2 class="card-title">Current User:</h2>
      <%= debug Current.identity.inspect %>
    </div>
  </div>

  <div class="mt-4 card bg-base-100 card-sm shadow-sm">
    <div class="card-body">
      <h2 class="card-title">Current Account:</h2>
      <%= debug Current.account.inspect %>
      <div class="flex gap-4 items-center">
        <span class="text-lg font-bold">Switch to other account:</span>
        <% Current.identity.accounts.each do |account| %>
          <%= link_to account.name, root_path(script_name: account.slug_path), class: "btn btn-primary btn-sm", disabled: Current.account.id == account.id %>
        <% end %>
      </div>
    </div>
  </div>

  <% url = join_url(code: Current.account.join_code.code, script_name: Current.account.slug_path) %>
  <div class="mt-4 card bg-base-100 card-sm shadow-sm">
    <div class="card-body">
      <h2 class="card-title">Join Url:</h2>
      <div class="flex gap-4 items-center">
      <code>
        <%= url %>
      </code>
      <button class="btn btn-sm btn-outline relative" data-controller="copy-to-clipboard" data-action="copy-to-clipboard#copy" data-copy-to-clipboard-content-value="<%= url %>" data-copy-to-clipboard-success-class="btn-copied">
        <span class="copy-icon transition-opacity duration-300">
          <%= image_tag "copy.svg", class: "w-4 h-4" %>
        </span>
        <span class="copied-text absolute top-0 left-full text-success opacity-0 transition-opacity duration-300 pointer-events-none">
          Copied!
        </span>
      </button>
    </div>
    </div>
  </div>

  <div class="mt-4 card bg-base-100 card-sm shadow-sm">
    <div class="card-body">
      <h2 class="card-title">Payments:</h2>
      <%= button_to account_payment_path(plan_key: "first"), class: "btn btn-primary btn-sm", data: { turbo: false, controller: "button-loading" } do %>
        <span data-button-loading-target="text">Create Payment</span>
        <span data-button-loading-target="loading" class="hidden">
          <span class="loading loading-spinner loading-sm"></span>
          Processing...
        </span>
      <% end %>
    </div>
  </div>
</div>